kind: pipeline
name: e-bookstore

steps:
  - name: build
    image: maven
    volumes:
    - name: cache
      path: /root/.m2
    commands:
    - ls
    - pwd
    - cd /drone/src/demo
    - ls
    - mvn install
volumes:
  - name: cache
    host:
      path: /tmp/cache