kind: pipeline
name: e-bookstore

steps:
  - name: build
    image: maven
    // volumes:
    // - name: cache
    //   path: /cache
    commands:
    - ls
    - pwd
    - cd /drone/src/demo
    - ls
    // - mvn install
// volumes:
//   - name: cache
//     host:
//       path: /tmp/cache
