kind: pipeline
name: e-bookstore

steps:
  - name: build
    image: maven:3.6.1-jdk-8-slim
    volumes:
    - name: cache
      path: /root/.m2
    commands:
    - ls
    - pwd
    - cd /drone/src/demo
    - ls
    - mvn install -Dmaven.test.skip=true
volumes:
- name: cache
  host:
    path: /home/ubuntu/.m2
    